### ISSUE TITLE
The unique modifier is optional now

### ISSUE THREAD

**Issue by zetashift** [kylegoetz/tree-sitter-unison#54]
Parsing breaks because the unique modifier now isn't required:

```
type core.Recipe = {
  metadata: [Text],
  description: Text,
  ingredients: [Text],
  steps: [Step]
}
```

![image](https://github.com/kylegoetz/tree-sitter-unison/assets/1857826/53504552-be01-4be0-b96f-8c4401599057)

**Comment by zetashift** [comment]
Glancing at the code, is the change required to fix this here?
https://github.com/kylegoetz/tree-sitter-unison/blob/master/grammar/type.js#L61
and if it's omitted it's a `unique` type?

**Comment by kylegoetz** [comment]
Thanks for the catch! I knew there was discussion about defaulting to `unique` but didn't know it was official yet!

Yes, I will do a fix for this right now. Shouldn't be hard.

**Comment by kylegoetz** [comment]
gonna lump in a couple other things and do a new version bump + deploy
