### ISSUE TITLE
Consider committing `grammar.json`

### ISSUE THREAD

**Issue by clason** [kylegoetz/tree-sitter-unison#56]
While keeping `parser.c` out of version control is reasonable (and in fact recommended by upstream), the generated `grammar.json` is much smaller and has meaningful diffs. The benefit of keeping this in the repo is that downstream users (like nvim-treesitter) do not require `node` for building and can just do `tree-sitter g src/grammar.json && tree-sitter build -o parser.so` (which is what nvim-treesitter is transitioning to for 1.0).

In addition, consider making proper releases including the generated artifacts (which is what nvim-treesitter will require for "stable" parsers). Upstream is in the process of adding reusable workflows and `tree-sitter` support to make this easier.

**Comment by kylegoetz** [comment]
This is a good idea. I tried to keep a separate branch for artifacts but it's just kind of a hassle. I'll look into what's need for these proper releases, too.

**Comment by clason** [comment]
https://github.com/tree-sitter/workflows

**Comment by kylegoetz** [comment]
@clason wanted to thank you for the pointers to workflows, I followed it and have CI set up, including a fuzzer, and the fuzzer caught memory leaks that I've since fixed. You made my code better!
