### ISSUE TITLE
Enable use in WASM by replacing usages of `strcat` with `strncat`

### ISSUE THREAD

**Issue by maxbrunsfeld** [kylegoetz/tree-sitter-unison#57]
When compiling Tree-sitter grammars to WASM, only a limited set of functions from the C stdlib are available. The list of functions is defined here: https://github.com/tree-sitter/tree-sitter/blob/master/lib/src/wasm/stdlib-symbols.txt.

One use case for compiling grammars to WASM is adding them as extensions to the [Zed](https://github.com/zed-industries/zed) editor. @zetashift has begun work on a Unison extension for Zed, here: https://github.com/zetashift/unison-zed.

It looks like the WASM build is currently failing due to a use of `strcat`. This function is not available under Tree-sitter's WASM runtime, but its safer cousin, `strncat` is (as of the latest master branch of Tree-sitter).

To check that the grammar works in WASM, you can run the `tree-sitter build-wasm` command. This might be a good thing to do in CI.

Note that the `strncat` function was just added on `master`, and isn't yet in the latest release.

**Comment by kylegoetz** [comment]
Hm, building breaks with strncat because my platform (OSX) requires a third argument. I need to look into this.

**Comment by maxbrunsfeld** [comment]
Yeah, `strncat` takes a length argument.
