### ISSUE TITLE
bounds checking for Int, Nat, and Float

### ISSUE THREAD

**Issue by kylegoetz** [kylegoetz/tree-sitter-unison#73]
tree sitter folks have argued persuasively that bounds-checking doesn't belong in a parser at all. An out-of-bounds Float gets pretty printed as Infinity by ucm. Have active question out to Unison staff whether Infinity is a separate type (and thus needs its own node and bounds checking is a must) or not (can strip out bounds checking per exhortation from tree sitter folks).

Tagging @zetashift because if this issue results in removing bounds checking, then `atof` will leave the codebase and that should result in a TSG that can be compiled successfully to WASM for Zed, and their PR into Zed can be updated and should smoothly be accepted.

**Comment by zetashift** [comment]
Thank you for tagging me, and more importantly, thank you for all your effort and time!

**Comment by kylegoetz** [comment]
fixed by #74
